apiVersion: v1
kind: ConfigMap
metadata:
  name: test-template-values
data:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  clusterLabels: |
    # configmaps can only contain strings, toJson for debug:
    {{ .Values.clusterLabels | toJson }}
  clusterValues: |-
    {{ .Values.clusterValues | toJson }}
  global: |-
    {{ .Values.global | toJson }}
  annotations: |-
    {{ .Values.annotations | toJson }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
